### PR TITLE
Speedup using Numba

### PR DESCRIPTION
**Pull request by ShrirajHegde**
Remove flickering in UNIX systems.

### CODE REVIEW

**Comment by TinkeringPenguin** [comment]
Interesting 🤔
Will need a requirements.txt tho

**Comment by ShrirajHegde** [comment]
Numba is the only additional dependency.

https://numba.pydata.org/

**Comment by TinkeringPenguin** [comment]
I know but do a `pip freeze > requirements.txt` so it's installed although I think most people cloning this would be confused on installing a new python package

**Comment by TinkeringPenguin** [comment]
Still very cool stuff tho!

**Comment by ShrirajHegde** [comment]
> I know but do a `pip freeze > requirements.txt` so it's installed although I think most people cloning this would be confused on installing a new python package

Here's pip freeze for python 3.10

```
llvmlite==0.39.1
numba==0.56.4
numpy==1.23.5
```

**Pull request closed without merging**
